### PR TITLE
Remove trailing hyphens and payload on series name

### PR DESCRIPTION
**Pull request by meganemura**
"達人伝" is separated into 2 series.
https://amakan.net/series/24781
https://amakan.net/series/6907

This fixes, but it may also affect to the correct series like ["NARUTO -ナルト-"](http://www.naruto.com/j/).
Is it acceptable?

### CODE REVIEW

**Comment by meganemura** [comment]
Close this since "D.Gray-man 25 (ジャンプコミックス)" -> "D.Gray" 😩

**Comment by r7kamura** [comment]
Thanks @meganemura, I just added a test case for D.Gray-man for now. https://github.com/amakan/amakanize/commit/07981982ad792d4407cac51f9dabbd561b238a97

**Comment by r7kamura** [comment]
I think there is a specific difference between `"D.Gray-man"` and `"達人伝 -9万里を風に乗り-"` that the latter has a space before the 1st hyphen, so what we should do is to distinguish `x x-x-x x` from `x -x- x`.

```rb
"達人伝 -9万里を風に乗り-".gsub(/\s+-\S+-/, "") #=> "達人伝"
"D.Gray-man 25".gsub(/\s+-\S+-/, "") #=> "D.Gray-man 25"
```

The problem of this approach is we can't detect `"達人伝"` from `"達人伝-9万里を風に乗り-"`.

```rb
"達人伝-9万里を風に乗り-".gsub(/\s+-\S+-/, "") #=> "達人伝-9万里を風に乗り-"
```

**Comment by r7kamura** [comment]
@meganemura 「達人伝」シリーズ - amakan https://amakan.net/series/24781 🎉

**Comment by meganemura** [comment]
Thank you for fixing it! 😊

**Pull request closed without merging**
